testing runner job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,8 +4,11 @@ version: 2.1
 # denotes that it is setup workflow
 setup: true
 
-#            HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X GET https://runner.circleci.com/api/v2/tasks?resource-class=test_runner/m1Pro
-#              -H 'Circle-Token: "${RUNNER_API_TOKEN}"')
+parameters:
+  runner_threshold:
+    type: string
+    default: '2'
+    description: The amount of queued jobs until moving to cloud resources
 
 jobs:
   check_queue_depth:
@@ -28,6 +31,16 @@ jobs:
                echo "jq is required to use this command"
                exit 1
             fi
+            
+            if [ -z "${CIRCLE_CONTINUATION_KEY}" ]; then
+              echo "CIRCLE_CONTINUATION_KEY is required. Make sure setup workflows are enabled."
+              exit 1
+            fi
+
+            if [ -z "${CONFIG_PATH}" ]; then
+              echo "CONFIG_PATH is required."
+              exit 1
+            fi
                      
             HTTP_RESPONSE=$(curl -f -s -X GET -H "Circle-Token:${RUNNER_API_TOKEN}" --write-out "HTTPSTATUS:%{http_code}" "https://runner.circleci.com/api/v2/tasks?resource-class=test_runner/m1Pro")         
             
@@ -46,17 +59,60 @@ jobs:
             UNCLAIMED_TASK_COUNT=$(echo $HTTP_BODY | jq ".unclaimed_task_count")
             
             echo "$UNCLAIMED_TASK_COUNT"
+                     
+            USE_RUNNER=true         
+            
+            if [ $UNCLAIMED_TASK_COUNT -gt <<parameters.runner_threshold>> ];then
+              USE_RUNNER=false
+            fi
+            
+            PARAMS=$(jq --null-input \
+              --arg use_runner "$USE_RUNNER" \
+              '{"use_runner": $USE_RUNNER}')
+          
+                     
+                     
+            if ! jq . >/dev/null 2>&1 \<<<"$PARAMS"; then
+              echo "PARAMETERS aren't valid json"
+              exit 1
+            fi
+                     
+                     
+            mkdir -p /tmp/circleci
+                     
+            rm -rf /tmp/circleci/continue_post.json
+            
+            
+            # Escape the config as a JSON string.
+                     
+            jq -Rs '.' ".circleci/continue-config.yml" > /tmp/circleci/config-string.json
+                     
+                     
+            jq -n \
+                --arg continuation "$CIRCLE_CONTINUATION_KEY" \
+                --arg params "$PARAMS" \
+                --slurpfile config /tmp/circleci/config-string.json \
+                '{"continuation-key": $continuation, "configuration": $config|join("\n"), "parameters": $params|fromjson}' > /tmp/circleci/continue_post.json
+
+            cat /tmp/circleci/continue_post.json
+
+
+            [ [ $(curl \
+                  -o /dev/stderr \
+                  -w '%{ http_code }' \
+                    -XPOST \
+                    -H "Content-Type: application/json" \
+                    -H "Accept: application/json"  \
+                    --data @/tmp/circleci/continue_post.json \
+                    "https://circleci.com/api/v2/pipeline/continue") \
+               -eq 200 ]]
 
             
             
             
             
 
-  test_runner:
-    machine: true
-    resource_class: test_runner/m1Pro
-    steps:
-      - run: echo "Hi I'm on Runners!"
+
 
 workflows:
    main:
